config/routes.rb
Rails.application.routes.draw do
  resources :tasks do
  	member do
  		patch :complete
  	end
  end

  resources :tags, only: [:index, :show]

  root 'tasks#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
	acts_as_taggable_on :tags

	def completed?
		!completed_at.blank?
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @tags = ActsAsTaggableOn::Tag.all
  end

  def show
    @tag =  ActsAsTaggableOn::Tag.find(params[:id])
    @tasks = Task.tagged_with(@tag.name)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy, :complete]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def complete
    @task.update_attribute(:completed_at, Time.now)
    redirect_to tasks_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:title, :deadline, :tag_list)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/acts_as_taggable_on/tags/_tag.html.erb
<%= link_to tag.name, tag_path(tag) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Task Management App</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href='http://fonts.googleapis.com/css?family=Lato:300,400,700' rel='stylesheet' type='text/css'>
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
  </head>

  <body>
  	<div class="container">
    	<%= yield %>
    </div>
  </body>
</html>

app/views/tags/index.html.erb
<h1>Tags</h1>
<%= render @tags %>

app/views/tags/show.html.erb
<h1 class="task_title"><%= @tag.name %></h1>
<div id="tasks_wrapper">
  <%= render @tasks %>
</div>
<div class="links">
	<%= link_to 'Back', tasks_path %>
</div>

app/views/tasks/_form.html.erb
<%= form_with(model: task, local: true) do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :task_title %>
  </div>

  <div class="field">
    <%= form.label :deadline %>
    <%= form.date_field :deadline, :id => "datepicker" %>
  </div>

  <div class="field">
    <%= form.label :tags %>
    <%= form.text_field :tag_list, value: form.object.tag_list.to_s %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<script>
$('#datepicker').datepicker({format: 'dd/mm/yyyy'});
</script>

app/views/tasks/_task.html.erb
<div class="row clearfix">
	<% if task.completed? %>
		<div class="task">
			<p style="opacity: 0.4;"><strike><%= link_to task.title, task %></strike></p>
			<p>Due: <%= task.deadline %></p>
			<p>Tags: <%= render task.tags %></p>
		</div>
		<div class="complete">
			<%= link_to complete_task_path(task), method: :patch do %>
				<i class="fa fa-check"></i>
			<% end %>
		</div>
		<div class="trash">
			<%= link_to task_path(task), method: :delete, data: { confirm: "Are you sure?" } do %>
				<i class="fa fa-trash"></i>
			<% end %>
		</div>
	<% else %>
		<div class="task">
			<p><%= link_to task.title, task %></p>
			<p>Due: <%= task.deadline %></p>
			<p>Tags: <%= render task.tags %></p>
		</div>
		<div class="complete">
			<%= link_to complete_task_path(task), method: :patch do %>
				<i class ="fa fa-check"></i>
			<% end %>
		</div>
		<div class="trash">
			<%= link_to task_path(task), method: :delete, data: { confirm: "Are you sure?" } do %>
				<i class="fa fa-trash"></i>
			<% end %>
		</div>
	<% end %>
</div>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>
<h1 class="task_title">Task List</h1>
<div id="tasks_wrapper">
  <%= render @tasks %>
</div>


<!--
<% @tasks.each do |task| %>
  <div class="row clearfix">
    <div class="todo_item">
      <p><%= task.title %></p>
    </div>
  </div>
<% end %> -->

<div class="links">
  <%= link_to "New Task", new_task_path %>
</div>
<!---


<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Deadline</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.title %></td>
        <td><%= task.deadline %></td>
        <td><%= link_to 'Show', task %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Mark as Complete', complete_task_path(task), method: :patch %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task', new_task_path %> -->

app/views/tasks/new.html.erb
<h1 class="task_title">New Task</h1>

<div class="forms">
	<%= render 'form', task: @task %>
</div>
<div class="links">
	<%= link_to 'Back', tasks_path %>
</div>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<h2 class="task_title"><%= @task.title %></h2>

<p>Deadline: <%= @task.deadline %></p>

<p>Tags: <%= render @task.tags %></p>

<div class="links">
<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>
</div>